/*
 * MainWindow.java
 *
 * Created on 20 September 2013, 8:50 AM
 */

package gui;

import java.util.Random;
/**
 *
 * @author  90045985
 */
public class MainWindow extends javax.swing.JFrame {
    private Mode mode;
    private String path;
    private int port;
    private long clientID;
    private ContractorTableModel tableData;
    private ViewController controller;
    
    public MainWindow(){
        initComponents();
    }
    
    /** Creates new form MainWindow */
    public MainWindow(String path, int port, Mode mode) {
        this();
        this.toFront();
        genClientID();
        this.mode = mode;
        controller = new ViewController(path, port, mode);
        tableData = controller.getContractors();
        setUpTable();
        setVisible(true);
    }

    /** 
     * @param path      Path for database
     */
    public void setPath(String path){
        this.path = path;
        
    }
     
    /** 
     * @param port      Port for networking
     */
    public void setPort(int port){
        this.port = port;
    }
    
    /**
     * 
     * @param mode      Mode of operation. NETWORKED or DIRECT
     */
    public void setMode(Mode mode){
        this.mode = mode;
    }
    
     /** 
     * Generates a random number to be used as a Client ID when connecting to
     * the server.
     */
    private void genClientID(){
        Random r = new Random();
        clientID = r.nextLong();
    }
    
    
    /**
     * Used to help with jTable construction
     */
    private void setTableColumnSize(){
//        this.tblDisplay.getColumnModel().getColumn(1).setPreferredWidth(11);
//        this.tblDisplay.getColumnModel().getColumn(1).setPreferredWidth(11);
//        this.tblDisplay.getColumnModel().getColumn(2).setPreferredWidth(11);
//        this.tblDisplay.getColumnModel().getColumn(3).setPreferredWidth(11);
//        this.tblDisplay.getColumnModel().getColumn(4).setPreferredWidth(11);
//        this.tblDisplay.getColumnModel().getColumn(5).setPreferredWidth(11);
        
    }
    
    /**
     * Adds a table model to the jTable.  Method can be used to refresh the
     * table after the model has been updated
     */
    private void setUpTable(){
        this.tblDisplay.setModel(tableData);
        setTableColumnSize(); //Method not finished!!!!!
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgWarning = new javax.swing.JOptionPane();
        dlgBookContractor = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        txtCustomerNo = new javax.swing.JTextField();
        lblCustNoMessage = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplay = new javax.swing.JTable();
        txtSearchName = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();
        chkLocation = new javax.swing.JCheckBox();
        chkName = new javax.swing.JCheckBox();
        btnShowAll = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearchLocation = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();

        jLabel3.setText("Customer No.");

        lblCustNoMessage.setText("Enter an 8 digit customer number, or leave blank to clear booking");
        lblCustNoMessage.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSubmit.setMnemonic('S');
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgBookContractorLayout = new javax.swing.GroupLayout(dlgBookContractor.getContentPane());
        dlgBookContractor.getContentPane().setLayout(dlgBookContractorLayout);
        dlgBookContractorLayout.setHorizontalGroup(
            dlgBookContractorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgBookContractorLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCustomerNo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblCustNoMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        dlgBookContractorLayout.setVerticalGroup(
            dlgBookContractorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgBookContractorLayout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addGroup(dlgBookContractorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCustomerNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit))
                .addGap(27, 27, 27)
                .addComponent(lblCustNoMessage))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("All About Improvement Ltd.");

        tblDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDisplay);

        txtSearchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchNameActionPerformed(evt);
            }
        });

        btnSearch.setMnemonic('s');
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnAdd.setMnemonic('A');
        btnAdd.setText("Add Record");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnBook.setMnemonic('b');
        btnBook.setText("Book Selected");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        btnShowAll.setMnemonic('o');
        btnShowAll.setText("Show All Records");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("Location");

        btnDelete.setMnemonic('D');
        btnDelete.setText("Delete Record");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1))
                            .addComponent(chkLocation))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 683, Short.MAX_VALUE)
                        .addComponent(btnShowAll))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 501, Short.MAX_VALUE)
                        .addComponent(btnBook))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearchLocation)
                            .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)
                        .addGap(0, 529, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSearch))
                            .addComponent(chkName))
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearchLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkLocation)))
                    .addComponent(btnShowAll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete)
                    .addComponent(btnBook))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchNameActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
// After writing to database, update table view  
//    tableData = controller.getContractors();
//    setUpTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        tableData = controller.getContractors();
        setUpTable();
    }//GEN-LAST:event_btnShowAllActionPerformed

private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed

    //Check if a record is selected!
    if(tblDisplay.getSelectedRow() != -1){
        
        dlgBookContractor.setSize(450, 125);
        dlgBookContractor.setVisible(true);


    

// After writing to database, update table view  
//    tableData = controller.getContractors();
//    setUpTable();
    }
    else{
        //joptionPane - please select a row
        dlgWarning.showMessageDialog(this, "Please select a Contractor from the table","No Record Selected",javax.swing.JOptionPane.ERROR_MESSAGE);
    }
        
}//GEN-LAST:event_btnBookActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
//opens a dialog to accept the new record details
       //checks length of fields - no booking is taken when creating so only
       //name fields etc no customer at this point
        
       // calls controller.newContractor
        //window stays open until method runs and primary key is checked.
        //checks primary key.
        //if record exists the flag is checked - must read the record from the
        //file to check! - if is valid then an exception will be sent back.
        // if file is deleted then only the flag is changed.
        
        //if duplicate primary key, - this opens a
        // dialog to acknowledge and you must fix the details before submitting
        //again
        
        
        
        // After writing to database, update table view  
//    tableData = controller.getContractors();
//    setUpTable();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
    // Make sure id is 8 chars long and is a digit or blank.  
    //when booking you must enter a number because blank means available

        if(txtCustomerNo.getText().equals("")){
            
            //will need to pass in a string of 8 spaces i.e. "        "
            //get details from table
            //pass into contractor.bookRecord()
                
    //pulls the rest of the records details from the table and calls 
    //controller.bookContractor() to do the writing. or does it only pull the
            //fields needed for a match on the primary key?
    
    //closes jDialog.
            
            System.out.println("booking record");
            dlgBookContractor.dispose();
        }
        else if(txtCustomerNo.getText().length() == 8){
            try{
                //use parseInt() to check that the text is a number.
                int tempCustNo = Integer.parseInt(txtCustomerNo.getText());
                System.out.println("booking record");
                // call the method passing in the temp no.             
                //get details from table
            //pass into contractor.bookRecord()
            dlgBookContractor.dispose();
                
            }catch(NumberFormatException nfe){
                txtCustomerNo.setText("");
                lblCustNoMessage.setText("Please enter a valid customer no.");
            }
        }
        else{
            txtCustomerNo.setText("");
            lblCustNoMessage.setText("Please enter a valid customer no.");
        }
        
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox chkLocation;
    private javax.swing.JCheckBox chkName;
    private javax.swing.JDialog dlgBookContractor;
    private javax.swing.JOptionPane dlgWarning;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustNoMessage;
    private javax.swing.JTable tblDisplay;
    private javax.swing.JTextField txtCustomerNo;
    private javax.swing.JTextField txtSearchLocation;
    private javax.swing.JTextField txtSearchName;
    // End of variables declaration//GEN-END:variables

}
