/*
 * DBLocationInput.java
 *
 * Created on 20 September 2013, 8:51 AM
 */

package gui;

import java.io.*;

    

/**
 *
 * @author  90045985
 */
public class NetworkDBLocation extends javax.swing.JDialog {
    private static final String PROPERTIES_FILE_NAME = "suncertify.properties";
    private File file;
    private Config properties;
    private String path;
    private int port;
    private MainWindow view;
    
    
     /** Creates new form DBLocationInput with access to the MainWindow object
      */
    public NetworkDBLocation(java.awt.Frame parent, boolean modal, 
            MainWindow view) {
        this(parent, modal);
        this.view = view;   
    }
    
    /** Creates new form DBLocationInput */
    public NetworkDBLocation(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadConfig();
    }
    
 /**
 *
 * Looks for a Config file in the local directory.  If one is found the port 
 * and path will be loaded into the txtboxes.
 */
    void loadConfig(){
        file = new File(PROPERTIES_FILE_NAME);
        if(file.exists()){     
            try{
                //Loading Config
                FileInputStream fis = new FileInputStream(file);
                ObjectInputStream ois = new ObjectInputStream(fis);
                properties = (Config)ois.readObject();
                ois.close();
                fis.close();
            }catch(IOException ioe){
            // code for handling exception
                System.out.println("Error loading config\n" + ioe);
            }
            catch(Exception e){
            // code for handling exception
                System.out.println("Error loading config\n" + e);
            }
            
            if (!properties.getNetworkPath().equals("")){
                txtPath.setText(properties.getNetworkPath());
            }
            
            if(properties.getPort() > 0 ){
                txtPort.setText(String.valueOf(properties.getPort()));
            }
        }
        
    }
    
    /**
 *
 * Saves the current database location and port settings from
 * txtPath and txtPort to a Config object.

 */
    void savConfig(){
        path = txtPath.getText();
        
        if(!txtPort.getText().equals("")){
            port = Integer.parseInt(txtPort.getText());
        }
        
        //If a File object hasnt been set, one is created
        if(file == null){
            file = new File(PROPERTIES_FILE_NAME);
        }
        //If a Config object hasnt been set, one is created
        if(properties == null){
            properties = new Config();
        }
        
        properties.setNetworkPath(path);
        properties.setPort(port);
        
        try{
            //Serializing and saving the Config object
            FileOutputStream fos = new FileOutputStream(file);
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(properties);
            oos.close();
            fos.close();
            
        }catch(IOException ioe){
            //Exception Handling HERE
            System.out.println("Error saving config\n" + ioe);
        }
        catch(Exception e){
            // code for handling exception
            System.out.println("Error saving config\n" + e);
        }
    }
    
 /**
 * Method tests whether the <code>port</code> is valid
 * 
 * @param port      Port to be used in networking
 * @return boolean is the port valid or not         
 */
     public boolean isValidPort(String port){
        if(port.length()> 4 || port.equals("")){
            return false;
        }
        else{
            try{
            Integer.parseInt(port);
            return true;
         
            }catch(NumberFormatException nfe){
                return false; 
            }
         }
     }   
        

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        lblPath = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        txtPath = new javax.swing.JTextField();
        btnConnect = new javax.swing.JButton();
        lblPort = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Connect to Network Database");

        btnExit.setMnemonic('x');
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblPath.setText("Database Path:");

        lblMessage.setText("Please enter the location of your database.");
        lblMessage.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnConnect.setMnemonic('S');
        btnConnect.setText("Connect");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        lblPort.setText("Server Port:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConnect)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPath)
                            .addComponent(lblPort))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPath)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPort)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnConnect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(lblMessage))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
    savConfig();
    System.exit(0);
}//GEN-LAST:event_btnExitActionPerformed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
     if(!(new File(txtPath.getText()).isFile()) && !isValidPort(txtPort.getText())){
        txtPath.setText("");
        txtPort.setText("");
        lblMessage.setText("The file and port you entered are invalid.  Please enter the location of your database.");
     }
     else if(!(new File(txtPath.getText()).isFile())){
        txtPath.setText("");
        lblMessage.setText("The File you entered does not exist.  Please enter the location of your database.");
    }
     else if(!isValidPort(txtPort.getText())){
        txtPort.setText("");
        lblMessage.setText("You must enter a valid port.  Please enter the location of your database.");
    }
    else{
        savConfig();
        view.setPath(path);
        view.setPort(port);
        this.dispose();

        }
    }//GEN-LAST:event_btnConnectActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NetworkDBLocation dialog = new NetworkDBLocation(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        //savConfig(); //How can I get this to work?
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPath;
    private javax.swing.JLabel lblPort;
    private javax.swing.JTextField txtPath;
    private javax.swing.JTextField txtPort;
    // End of variables declaration//GEN-END:variables

}
